<?php
require_once __DIR__ . '/../vendor/autoload.php'; // Adjust path to mPDF if needed
require_once '../login_feature/db.php';

session_start();

// Fetch teacher info
$teacherId = $_SESSION['user_id'] ?? null;
if (!$teacherId) {
    die("Unauthorized access.");
}

$stmtUser = $pdo->prepare("SELECT * FROM teacher WHERE id = ?");
$stmtUser->execute([$teacherId]);
$user = $stmtUser->fetch(PDO::FETCH_ASSOC);
$teacherName = $user ? $user['firstname'] . ' ' . $user['lastname'] : 'Unknown';

// Fetch attendance report data filtered by teacher_id
// Assuming attendance_reports table has a teacher_id column
$stmt = $pdo->prepare("SELECT * FROM attendance_reports WHERE teacher_id = ?");
$stmt->execute([$teacherId]);
$reports = $stmt->fetchAll(PDO::FETCH_ASSOC);

// Start HTML content
$html = '
<style>
    body { font-family: sans-serif; font-size: 12px; }
    .header { text-align: center; font-size: 16px; font-weight: bold; margin-bottom: 10px; }
    table { width: 100%; border-collapse: collapse; margin-top: 10px; }
    th, td { border: 1px solid #000; padding: 5px; text-align: center; }
</style>

<div class="header">Attendance Reports</div>
<p><strong>Generated by:</strong> ' . htmlspecialchars($teacherName) . '</p>
<table>
    <thead>
        <tr>
            <th>Student ID</th>
            <th>Student Name</th>
            <th>Section</th>
            <th>Absent</th>
            <th>Present</th>
            <th>Tardiness</th>
            <th>Date & Time</th>
        </tr>
    </thead>
    <tbody>';

foreach ($reports as $row) {
    $html .= '<tr>
        <td>' . htmlspecialchars($row['student_id']) . '</td>
        <td>' . htmlspecialchars($row['student_name']) . '</td>
        <td>' . htmlspecialchars($row['section']) . '</td>
        <td>' . (int)$row['absent'] . '</td>
        <td>' . (int)$row['present'] . '</td>
        <td>' . (int)$row['tardiness'] . '</td>
        <td>' . htmlspecialchars($row['report_date']) . '</td>
    </tr>';
}

$html .= '</tbody></table>';

// Add signature
$html .= '<br><br><p><strong>Teacher Signature:</strong> _______________________</p>';

// Generate PDF
$mpdf = new \Mpdf\Mpdf();
$mpdf->SetTitle('Teacher Attendance Report');
$mpdf->WriteHTML($html);
$mpdf->Output('Attendance_Report.pdf', 'I'); // 'I' for inline preview; use 'D' to force download
